# Generated by Django 4.2.6 on 2023-11-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippet',
            new_name='summary',
        ),
    ]
